<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Masuk_1</name>
   <tag></tag>
   <elementGuidId>591e245e-e43f-4841-b283-d32b29bd9998</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;bs-example-navbar-collapse-1&quot;]/div/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;bs-example-navbar-collapse-1&quot;]/div/ul/li[2]/a</value>
      <webElementGuid>f3ec6f6d-685b-48dc-969c-909fb42c970a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
